#%RAML 1.0 SecurityScheme
displayName: custom-security
type: x-customSecurity
description: Custom security to validate API security
describedBy:
      headers:
        Authorization:
          description: |
             Used to send a valid access token.
          type: string
          required: true
        responses:
          401:
            description: Unauthorized. Bad or expired token.