#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: The API supports OAuth 2.0 security policy for all methods

describedBy:
  headers:
      Authorization:
        description: Used to send a valid OAuth 2 access token.
        type: string
        example: Bearer 131321
  queryParameters:
    access_token:
      description: |
         Used to send a valid OAuth 2 access token. Do not use with
         the "Authorization" header.
      type: string
  responses:
    401:
      description: |
        Bad or expired token. This can happen if the API consumer uses a revoked or expired access token. To fix, you should re-authenticate the user.
    403:
       description: |
        Bad OAuth request.
settings:
  authorizationUri: https://www.test.com/oauth2/authorize
  accessTokenUri: https://www.test.com/oauth2/access_token
  authorizationGrants: implicit