#%RAML 1.0 Trait
usage: Apply this trait to all methods to enforce security.

secured:
    headers:
      X-Token:
        description: A valid JWT token is required for accessing the API
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
        required: true
    responses:
      401:
        description: Unauthorized
